export const REGIONS = ['北部', '中部', '南部', '東部', '離島'] as const
export type Region = typeof REGIONS[number]

export const BRANCHES = [
  { code: "002", name: "基隆分行", region: "北部" as const },
  { code: "003", name: "中和分行", region: "北部" as const },
  { code: "004", name: "南港分行", region: "北部" as const },
  { code: "005", name: "台北分行", region: "北部" as const },
  { code: "006", name: "民權分行", region: "北部" as const },
  { code: "007", name: "古亭分行", region: "北部" as const },
  { code: "008", name: "長安分行", region: "北部" as const },
  { code: "009", name: "士林分行", region: "北部" as const },
  { code: "010", name: "三重分行", region: "北部" as const },
  { code: "011", name: "宜蘭分行", region: "北部" as const },
  { code: "012", name: "羅東分行", region: "北部" as const },
  { code: "013", name: "桃園分行", region: "北部" as const },
  { code: "014", name: "中壢分行", region: "北部" as const },
  { code: "015", name: "石門分行", region: "北部" as const },
  { code: "016", name: "新竹分行", region: "北部" as const },
  { code: "017", name: "竹東分行", region: "北部" as const },
  { code: "018", name: "花蓮分行", region: "東部" as const },
  { code: "019", name: "玉里分行", region: "東部" as const },
  { code: "020", name: "苗栗分行", region: "北部" as const },
  { code: "021", name: "頭份分行", region: "北部" as const },
  { code: "022", name: "豐原分行", region: "中部" as const },
  { code: "023", name: "大甲分行", region: "中部" as const },
  { code: "024", name: "台中分行", region: "中部" as const },
  { code: "025", name: "南投分行", region: "中部" as const },
  { code: "026", name: "員林分行", region: "中部" as const },
  { code: "027", name: "斗六分行", region: "中部" as const },
  { code: "028", name: "北港分行", region: "南部" as const },
  { code: "029", name: "嘉義分行", region: "南部" as const },
  { code: "030", name: "新營分行", region: "南部" as const },
  { code: "031", name: "永康分行", region: "南部" as const },
  { code: "032", name: "台南分行", region: "南部" as const },
  { code: "033", name: "高雄分行", region: "南部" as const },
  { code: "034", name: "岡山分行", region: "南部" as const },
  { code: "035", name: "美濃分行", region: "南部" as const },
  { code: "036", name: "屏東分行", region: "南部" as const },
  { code: "037", name: "臺東分行", region: "東部" as const },
  { code: "038", name: "青年分行", region: "南部" as const },
  { code: "039", name: "金門分行", region: "離島" as const },
  { code: "040", name: "澎湖分行", region: "南部" as const },
  { code: "041", name: "營業部", region: "北部" as const },
  { code: "045", name: "和平分行", region: "北部" as const },
  { code: "046", name: "潮州分行", region: "南部" as const },
  { code: "047", name: "彰化分行", region: "中部" as const },
  { code: "048", name: "中山分行", region: "南部" as const },
  { code: "049", name: "永和分行", region: "北部" as const },
  { code: "050", name: "板橋分行", region: "北部" as const },
  { code: "051", name: "鳳山分行", region: "南部" as const },
  { code: "052", name: "湖口分行", region: "北部" as const },
  { code: "053", name: "蘇澳分行", region: "北部" as const },
  { code: "054", name: "新興分行", region: "南部" as const },
  { code: "055", name: "西台中分行", region: "中部" as const },
  { code: "056", name: "虎尾分行", region: "中部" as const },
  { code: "057", name: "仁愛分行", region: "北部" as const },
  { code: "058", name: "忠孝分行", region: "北部" as const },
  { code: "059", name: "中正分行", region: "南部" as const },
  { code: "061", name: "新店分行", region: "北部" as const },
  { code: "062", name: "北台南分行", region: "南部" as const },
  { code: "063", name: "松山分行", region: "北部" as const },
  { code: "064", name: "內湖分行", region: "北部" as const },
  { code: "065", name: "三民分行", region: "南部" as const },
  { code: "066", name: "民雄分行", region: "南部" as const },
  { code: "067", name: "大社分行", region: "南部" as const },
  { code: "069", name: "前鎮分行", region: "南部" as const },
  { code: "070", name: "路竹分行", region: "南部" as const },
  { code: "071", name: "五甲分行", region: "南部" as const },
  { code: "072", name: "太平分行", region: "中部" as const },
  { code: "074", name: "敦化分行", region: "北部" as const },
  { code: "076", name: "蘆洲分行", region: "北部" as const },
  { code: "077", name: "北臺中分行", region: "中部" as const },
  { code: "078", name: "苓雅分行", region: "南部" as const },
  { code: "079", name: "信義分行", region: "北部" as const },
  { code: "080", name: "土城分行", region: "北部" as const },
  { code: "081", name: "淡水分行", region: "北部" as const },
  { code: "082", name: "草屯分行", region: "中部" as const },
  { code: "083", name: "東台南分行", region: "南部" as const },
  { code: "084", name: "通霄分行", region: "北部" as const },
  { code: "085", name: "學甲分行", region: "南部" as const },
  { code: "086", name: "新莊分行", region: "北部" as const },
  { code: "087", name: "雙和分行", region: "北部" as const },
  { code: "089", name: "白河分行", region: "南部" as const },
  { code: "090", name: "復興分行", region: "北部" as const },
  { code: "091", name: "平鎮分行", region: "北部" as const },
  { code: "093", name: "文山分行", region: "北部" as const },
  { code: "094", name: "中港分行", region: "中部" as const },
  { code: "095", name: "東板橋分行", region: "北部" as const },
  { code: "096", name: "南崁分行", region: "北部" as const },
  { code: "097", name: "建國分行", region: "南部" as const },
  { code: "098", name: "樹林分行", region: "北部" as const },
  { code: "099", name: "東台北分行", region: "北部" as const },
  { code: "100", name: "西三重分行", region: "北部" as const },
  { code: "101", name: "南台中分行", region: "中部" as const },
  { code: "102", name: "長春分行", region: "北部" as const },
  { code: "103", name: "東新竹分行", region: "北部" as const },
  { code: "104", name: "新市分行", region: "南部" as const },
  { code: "105", name: "博愛分行", region: "南部" as const },
  { code: "106", name: "中崙分行", region: "北部" as const },
  { code: "107", name: "華江分行", region: "北部" as const },
  { code: "108", name: "竹北分行", region: "北部" as const },
  { code: "109", name: "安平分行", region: "南部" as const },
  { code: "110", name: "嘉興分行", region: "南部" as const },
  { code: "111", name: "南新莊分行", region: "北部" as const },
  { code: "112", name: "三峽分行", region: "北部" as const },
  { code: "113", name: "沙鹿分行", region: "中部" as const },
  { code: "114", name: "南桃園分行", region: "北部" as const },
  { code: "115", name: "汐止分行", region: "北部" as const },
  { code: "116", name: "萬華分行", region: "北部" as const },
  { code: "117", name: "小港分行", region: "南部" as const },
  { code: "118", name: "新工分行", region: "北部" as const },
  { code: "119", name: "烏日分行", region: "中部" as const },
  { code: "120", name: "西湖分行", region: "北部" as const },
  { code: "121", name: "八德分行", region: "北部" as const },
  { code: "122", name: "北屯分行", region: "中部" as const },
  { code: "123", name: "大安分行", region: "北部" as const },
  { code: "124", name: "北中壢分行", region: "北部" as const },
  { code: "125", name: "高樹分行", region: "南部" as const },
  { code: "126", name: "枋寮分行", region: "南部" as const },
  { code: "129", name: "光復分行", region: "北部" as const },
  { code: "130", name: "左營分行", region: "南部" as const },
  { code: "131", name: "北桃園分行", region: "北部" as const },
  { code: "132", name: "東港分行", region: "南部" as const },
  { code: "133", name: "天母分行", region: "北部" as const },
  { code: "134", name: "泰山分行", region: "北部" as const },
  { code: "135", name: "中科分行", region: "中部" as const },
  { code: "136", name: "大園分行", region: "北部" as const },
  { code: "137", name: "楊梅分行", region: "北部" as const },
  { code: "140", name: "城東分行", region: "北部" as const },
  { code: "141", name: "松南分行", region: "北部" as const },
  { code: "142", name: "福興分行", region: "中部" as const },
  { code: "143", name: "林口分行", region: "北部" as const },
  { code: "144", name: "西屯分行", region: "中部" as const },
  { code: "145", name: "內壢分行", region: "北部" as const },
  { code: "146", name: "竹南分行", region: "北部" as const },
  { code: "147", name: "安南分行", region: "南部" as const },
  { code: "148", name: "汐科分行", region: "北部" as const },
  { code: "149", name: "楠梓分行", region: "南部" as const },
  { code: "150", name: "大里分行", region: "中部" as const },
  { code: "151", name: "大灣分行", region: "南部" as const },
  { code: "153", name: "大發分行", region: "南部" as const },
  { code: "156", name: "工研院分行", region: "北部" as const },
  { code: "157", name: "北三重分行", region: "北部" as const },
  { code: "158", name: "圓通分行", region: "北部" as const },
  { code: "160", name: "大直分行", region: "北部" as const },
  { code: "161", name: "南屯分行", region: "中部" as const },
  { code: "163", name: "寶中分行", region: "北部" as const },
  { code: "164", name: "中清分行", region: "中部" as const },
  { code: "165", name: "南京東路分行", region: "北部" as const },
  { code: "166", name: "仁武分行", region: "南部" as const },
  { code: "167", name: "青埔分行", region: "北部" as const }
] as const

export type Branch = typeof BRANCHES[number]

export function searchBranches(query: string): Branch[] {
  const q = query.trim()
  if (!q) return []
  return BRANCHES.filter(
    b => b.code.startsWith(q) || b.name.includes(q)
  ).slice(0, 8)
}

export function findBranch(code: string): Branch | undefined {
  return BRANCHES.find(b => b.code === code)
}

